<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-06T22:14:15 IST" name="Default suite" finished-at="2021-07-06T22:17:19 IST" duration-ms="183546">
    <groups>
    </groups>
    <test started-at="2021-07-06T22:14:15 IST" name="Default test" finished-at="2021-07-06T22:17:19 IST" duration-ms="183546">
      <class name="com.bryne.qa.testcases.UpdateDetailsPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:14:17 IST" name="setup" finished-at="2021-07-06T22:14:43 IST" duration-ms="26327" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateUpdateFieldsTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:14:43 IST" name="validateUpdateFieldsTest" data-provider="getTestData" finished-at="2021-07-06T22:15:20 IST" duration-ms="36134" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abhishek]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Using]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9.00000003E8]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Karnatka]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[300023.0]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [300023.0] but found [3000230]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [300023.0] but found [3000230]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.bryne.qa.testcases.UpdateDetailsPageTest.validateUpdateFieldsTest(UpdateDetailsPageTest.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdateFieldsTest -->
        <test-method is-config="true" signature="aftermath()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:15:20 IST" name="aftermath" finished-at="2021-07-06T22:15:21 IST" duration-ms="1277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermath -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:15:21 IST" name="setup" finished-at="2021-07-06T22:15:43 IST" duration-ms="22223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateUpdateFieldsTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:15:43 IST" name="validateUpdateFieldsTest" data-provider="getTestData" finished-at="2021-07-06T22:16:18 IST" duration-ms="35407" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abhishek]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Using]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9.00000003E8]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Karnatka]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[300023.0]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [300023.0] but found [3000230]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [300023.0] but found [3000230]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.bryne.qa.testcases.UpdateDetailsPageTest.validateUpdateFieldsTest(UpdateDetailsPageTest.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdateFieldsTest -->
        <test-method is-config="true" signature="aftermath()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:16:18 IST" name="aftermath" finished-at="2021-07-06T22:16:20 IST" duration-ms="1361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermath -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:16:20 IST" name="setup" finished-at="2021-07-06T22:16:42 IST" duration-ms="22687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateUpdateFieldsTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:16:42 IST" name="validateUpdateFieldsTest" data-provider="getTestData" finished-at="2021-07-06T22:17:18 IST" duration-ms="35158" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abhishek]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Using]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9.00000003E8]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Karnatka]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[300023.0]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Bengaluru]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [300023.0] but found [3000230]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [300023.0] but found [3000230]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.bryne.qa.testcases.UpdateDetailsPageTest.validateUpdateFieldsTest(UpdateDetailsPageTest.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUpdateFieldsTest -->
        <test-method is-config="true" signature="aftermath()[pri:0, instance:com.bryne.qa.testcases.UpdateDetailsPageTest@6497b078]" started-at="2021-07-06T22:17:18 IST" name="aftermath" finished-at="2021-07-06T22:17:19 IST" duration-ms="1309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermath -->
      </class> <!-- com.bryne.qa.testcases.UpdateDetailsPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
